<form class="form-signin">
	<h2 class="form-signin-heading">Please sign up</h2>
	<input type="text" name="name" class="form-control" placeholder="Display name" required autofocus>
	<input type="text" name="email" class="form-control" placeholder="Email address" required autofocus>
	<input type="password" name="password" class="form-control" placeholder="Password" required>
	<label class="checkbox">
	</label>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
</form>