<!-- Example row of columns -->
<div class="row">
	<div class="col-md-4">
		<h2>About</h2>
		<p>Proyecto de PHP y MySQL del Curso de PHP, Zaragoza Oct/Nov 2013 (M)</p>
		<p>
			<a class="btn btn-default" href="/index/about" role="button">View details
				&raquo;</a>
		</p>
	</div>
	<div class="col-md-4">
		<h2>Contact</h2>
		<p>Formulario de contacto del proyecto.</p>
		<p>
			<a class="btn btn-default" href="/index/contact" role="button">Contact!
				&raquo;</a>
		</p>
	</div>
	<div class="col-md-4">
		<h2>Code & Project</h2>
		<p>Página Git Hub y Página Pivotaltrabker </p>
		<p>
			<a class="btn btn-default" href="/index/code" role="button">View details
				&raquo;</a>
		</p>
	</div>
</div>